# Generated by Django 4.2.7 on 2024-07-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "online"), ("offline", "offline")],
                        max_length=256,
                        verbose_name="Name",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.CreateModel(
            name="Gateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Serial Number"
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("ip_address", models.GenericIPAddressField(verbose_name="Ip Address")),
                ("device", models.ManyToManyField(to="gateway.device")),
            ],
            options={
                "verbose_name": "Gateway",
                "verbose_name_plural": "Gateways",
            },
        ),
    ]
