# Generated by Django 4.2.7 on 2024-06-28 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_phone_alter_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListedTokenAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=500)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_BlackListedTokenAccess",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
